[package]
name = "byexample"
version = "0.1.0"
authors = ["Peter Fitzgibbons <peter.fitzgibbons@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
typename = "0.1.1"