[package]
name = "rust_by_example"
version = "0.1.0"
authors = ["Peter Fitzgibbons <peter.fitzgibbons@ga-asi.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
typename = "0.1.1"
